### ISSUE TITLE
about the softmax function

### ISSUE THREAD

**Issue by yuanyuansiyuan** [HaojiHu/Sets2Sets#3]
When predicting the scores for every item in the set, you use softmax to normarlize the vector, but it will result in sum 1. 
In the multi-label classification, should we use the sigmoid function instead?
Actually, in my own multi-label classification experiment, i use the softmax on my output scores, the performance drops than no softmax.

**Comment by HaojiHu** [comment]
I think I tested this in my method. The reason I use softmax at that time is to make sure I can get distribution across all items then I can merge the prediction from the decoder and the repeated component. If you work on your case and get better performance, you can definitely use the sigmoid function.
