### ISSUE TITLE
Details about the OPTUM dataset

### ISSUE THREAD

**Issue by yuanyuansiyuan** [HaojiHu/Sets2Sets#5]
can you give more details about the OPTUM dataset used in this paper?
i wan t to know where can i get this dataset. Thank you very much.

**Comment by HaojiHu** [comment]
Sorry, it is not a public dataset and it is allowed to distribute it. If you want to find some similar dataset, I can provide some hints for you. This data is about EHR for diabetes patients. Usually, the state of patients with diabetes has some monotonic patten as diabetes are usually not curable and can only be maintained. That is some personalized temporal dynmiacs . Generally, I think EHR for patients with a specific chronic disease should be similar, e.g. Alzheimer.

**Comment by yuanyuansiyuan** [comment]
Thank you for your reply~
